### ISSUE TITLE
Not working with terraform 0.13.0

### ISSUE THREAD

**Issue by kanekotic** [terraform-google-modules/terraform-google-bastion-host#51]
Having issue due the latest version of terraform to integrate this module
```Error: Unsupported Terraform Core version

  on .terraform/modules/iap_bastion.instance_template/terraform-google-vm-3.0.0/modules/instance_template/versions.tf line 18, in terraform:

  18:   required_version = "~> 0.12.6"

Module module.iap_bastion.module.instance_template (from

terraform-google-modules/vm/google//modules/instance_template) does not

support Terraform version 0.13.0. To proceed, either choose another supported

Terraform version or update this version constraint. Version constraints are

normally set for good reason, so updating the constraint may lead to other

errors or unexpected behavior.

Error: Unsupported Terraform Core version

  on .terraform/modules/iap_bastion.instance_template/terraform-google-vm-3.0.0/modules/instance_template/versions.tf line 18, in terraform:

  18:   required_version = "~> 0.12.6"

Module module.iap_bastion.module.instance_template (from

terraform-google-modules/vm/google//modules/instance_template) does not

support Terraform version 0.13.0. To proceed, either choose another supported

Terraform version or update this version constraint. Version constraints are

normally set for good reason, so updating the constraint may lead to other

errors or unexpected behavior.```

**Comment by onetwopunch** [comment]
Thank you raising this concern. This should be fixed in v2.8.0 due to #53

**Comment by sdowns** [comment]
Still seeing the issue with the instance_template here:
```
Initializing modules...

Error: Unsupported Terraform Core version

  on .terraform/modules/iap_bastion.instance_template/modules/instance_template/versions.tf line 18, in terraform:
  18:   required_version = "~> 0.12.6"

Module module.iap_bastion.module.instance_template (from
terraform-google-modules/vm/google//modules/instance_template) does not
support Terraform version 0.13.2. To proceed, either choose another supported
Terraform version or update this version constraint. Version constraints are
normally set for good reason, so updating the constraint may lead to other
errors or unexpected behavior.
```

This would appear (to me as a novice terraform user) to be coming from the lines below in main.tf
```
module "instance_template" {
  source  = "terraform-google-modules/vm/google//modules/instance_template"
  version = "~> 3.0"
```

The instance_template submodule appears to have been updated in some of the v4 and v5 updates, but 3.0 has not been updated to allow terraform 0.13.

**Comment by MeNsaaH** [comment]
yes the version should be 
```hcl
terraform {
  required_version = ">= 0.12.6, <4.0"
  required_providers {
    google = ">= 2.7, <4.0"
  }
}
```

**Comment by onetwopunch** [comment]
@sdowns you are correct that this is an upstream issue. However, the most recent release of the`terraform-google-vm` (4.0.0) still does not support 13.0. I've opened https://github.com/terraform-google-modules/terraform-google-vm/issues/114 there and will work on fixing it momentarily

**Comment by MeNsaaH** [comment]
I see you've closed the issue @onetwopunch. Have you verified that they all the modules work with version 13

**Comment by onetwopunch** [comment]
I closed the issue since it was already fixed in master just hadn't been released yet. I triggered the release of version 5.0 and have now created https://github.com/terraform-google-modules/terraform-google-bastion-host/pull/55 which should hopefully fix it.

**Comment by kanekotic** [comment]
thanks @onetwopunch
